from __future__ import annotations
from dataclasses import dataclass
from typing import Protocol, Optional, runtime_checkable


@runtime_checkable
class PciDb(Protocol):
    def get_vendor_name(self, vendor_id: int) -> Optional[str]: ...
    def get_device_name(self, vendor_id: int, device_id: int) -> Optional[str]: ...
    def get_subsystem_name(
        self, vendor_id: int, device_id: int, subvendor_id: int, subdevice_id: int
    ) -> Optional[str]: ...
    def get_class_name(
        self, base: int, subclass: Optional[int] = None, prog_if: Optional[int] = None
    ) -> Optional[str]: ...
    def get_class_name_from_code(self, class_code_24bit: int) -> Optional[str]: ...
    def describe_device_best_effort(
        self, vendor_id: int, device_id: int, class_code_24bit: Optional[int]
    ) -> str: ...
    def close(self) -> None: ...
