name: tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up CPython (host)
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Preinstall interpreters for uv runs
        run: uv python install 3.10 3.11 3.12 3.13

      - name: Run tests
        run: bash run_tests.sh
        env:
          # For reproducible builds during `uv build --sdist` (Hatch hook):
          PCIID_FORCE_DOWNLOAD: "1"

      - name: Upload coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            .coverage.*
            coverage.xml
            htmlcov/
          if-no-files-found: ignore

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: python
          fail_ci_if_error: true
